import type { NewsItem } from "./types";

/**
 * Headlines and slugs mirror fclb.com.ua. Summaries are short editorial
 * standfirsts; the six most recent match the wording used on the live site.
 */
export const news: NewsItem[] = [
  {
    slug: "livyj-bereg-pryjmayemo-karpaty",
    title: "Лівий Берег. Приймаємо Карпати",
    titleEn: "Livyi Bereh. We host Karpaty",
    excerpt: "«Лелеки» зіграють у рідних стінах із лідером чемпіонату.",
    excerptEn: "The Storks take on the league leaders at home.",
    date: "2026-08-29",
    category: "УПЛ",
    image: "/media/matchday-upl.jpg",
  },
  {
    slug: "upl-vazhlyve-ochko-do-turnirnoyi-kopilky",
    title: "УПЛ. Важливе очко до турнірної копілки",
    titleEn: "UPL. A valuable point on the board",
    excerpt: "Лівий Берег зіграв унічию з Карпатами.",
    excerptEn: "Livyi Bereh drew with Karpaty.",
    date: "2026-08-29",
    category: "УПЛ",
  },
  {
    slug: "mogly-vyryvaty-peremogu-ryabokon-i-vorobchak-pro-match-iz-karpatamy",
    title: "«Могли виривати перемогу». Рябоконь і Воробчак про матч із Карпатами",
    titleEn: "“We could have taken it.” Ryabokon and Vorobchak on the Karpaty match",
    excerpt: "Коментарі після матчу чергового туру УПЛ.",
    excerptEn: "Reaction after the latest UPL round.",
    date: "2026-08-29",
    category: "УПЛ",
  },
  {
    slug: "match-upl-2-livyj-bereg-karpaty-pereneseno",
    title: "Матч УПЛ-2 Лівий Берег – Карпати перенесено",
    titleEn: "UPL-2 match Livyi Bereh – Karpaty postponed",
    excerpt: "Тривала атака російських БПЛА зірвала матч молодіжних команд.",
    excerptEn: "A prolonged Russian drone attack forced the youth fixture off.",
    date: "2026-08-30",
    category: "УПЛ-2",
    image: "/media/match-postponed.png",
  },
  {
    slug: "upl-2-pryjmayemo-yunakiv-karpat",
    title: "УПЛ-2. Приймаємо юнаків Карпат",
    titleEn: "UPL-2. Hosting the Karpaty youngsters",
    excerpt: "Молодь «лелек» прийматиме в рідних стінах одноліток з Карпат.",
    excerptEn: "The Storks' youth side welcomes their Karpaty peers.",
    date: "2026-08-29",
    category: "УПЛ-2",
    image: "/media/matchday-u21.jpg",
  },
  {
    slug: "naczionalna-liga-u19-zigrayemo-u-lvovi",
    title: "Національна ліга U19. Зіграємо у Львові",
    titleEn: "U19 National League. Away in Lviv",
    excerpt: "Команду Ковпака чекає непростий матч із Карпатами.",
    excerptEn: "Kovpak's side faces a tough trip to Karpaty.",
    date: "2026-09-02",
    category: "U19",
  },
  {
    slug: "nash-supernyk-v-1-16-finalu-kubka-ukrayiny-agrobines",
    title: "Наш суперник в 1/16 фіналу Кубка України – Агробізнес",
    titleEn: "Our cup opponent in the last 32 — Ahrobiznes",
    excerpt: "У 1/16 фіналу Кубка України «Лівий Берег» зіграє з тернопільським «Агробізнесом».",
    excerptEn: "In the Ukrainian Cup last 32 Livyi Bereh meet Ahrobiznes of Ternopil.",
    date: "2026-08-27",
    category: "Кубок",
  },
  {
    slug: "livyj-bereg-karpaty-kvytky-u-prodazhu-2",
    title: "Лівий Берег – Карпати: квитки у продажу!",
    titleEn: "Livyi Bereh – Karpaty: tickets on sale",
    excerpt: "Квитки на домашній матч чемпіонату вже доступні онлайн.",
    excerptEn: "Tickets for the home league match are now available online.",
    date: "2026-08-26",
    category: "Клуб",
  },
  {
    slug: "livyj-bereg-u19-my-vzhe-sered-lideriv",
    title: "Лівий Берег U19. Ми вже серед лідерів",
    titleEn: "Livyi Bereh U19. Already among the leaders",
    excerpt: "Юнацька команда впевнено закріпилася у верхній частині таблиці.",
    excerptEn: "The youth team has settled firmly near the top of the table.",
    date: "2026-08-25",
    category: "U19",
  },
  {
    slug: "arena-osokorky-novyj-etap-u-rozvytku-infrastruktury-livogo-berega",
    title: "Арена Осокорки – новий етап у розвитку інфраструктури",
    titleEn: "Arena Osokorky — a new stage for the club's infrastructure",
    excerpt: "Клуб оголосив про наступний інфраструктурний проєкт у Києві.",
    excerptEn: "The club has announced its next infrastructure project in Kyiv.",
    date: "2026-08-20",
    category: "Інфраструктура",
  },
  {
    slug: "ryabokon-sokolov-i-sidnnej-pro-nichyyu-z-kryvbasom",
    title: "Рябоконь, Соколов і Сідннней про нічию з Кривбасом",
    titleEn: "Ryabokon, Sokolov and Sidnei on the Kryvbas draw",
    excerpt: "Головний тренер і гравці — про виїзну нічию чемпіонату.",
    excerptEn: "The head coach and players on the away league draw.",
    date: "2026-08-16",
    category: "УПЛ",
  },
  {
    slug: "beton-kubok-ukrayiny-peremoga-na-pershomu-etapi",
    title: "BETON Кубок України. Перемога на першому етапі",
    titleEn: "BETON Ukrainian Cup. A win in the first stage",
    excerpt: "«Лівий Берег» упевнено подолав стартовий раунд національного кубка.",
    excerptEn: "Livyi Bereh eased through the opening round of the national cup.",
    date: "2026-08-13",
    category: "Кубок",
  },
];
